# Generated by Django 3.2.9 on 2021-11-14 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0002_alter_shortlongurl_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlongurl',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 23, 4, 25, 621574)),
        ),
    ]
