# Generated by Django 3.2.9 on 2021-11-14 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0005_alter_shortlongurl_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlongurl',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
