# Generated by Django 3.1.2 on 2021-11-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0006_alter_shortlongurl_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlongurl',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
